name: simple_peer
description: Simple WebRTC. Similar to the simple-peer project in javascript.
version: 0.0.13
repository: https://github.com/simonbengtsson/simple_peer_flutter

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
